### ISSUE TITLE
Valid agency timezone values ?

### ISSUE THREAD

**Issue by mhicauber** [afimb/chouette#15]
A GTFS file import with the "FR" value for the "agency_timezone" column in the "agencies.txt" file will fail. Digging into chouette tests, I see you're expecting values such as "Europe/Paris"

Google spec says valid values should be the ones listed here : https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
 (see https://developers.google.com/transit/gtfs/reference#agency_fields)

So "FR" value should be correct I think. Thank you for your feedback.

**Comment by metienne** [comment]
Chouette is in concordance with with FeedValidator and GTFSBook 
FR is not a TimeZone code but a Country code
see : http://gtfsbook.com/gtfs-book-sample.pdf

**Comment by mhicauber** [comment]
Oops - my bad. Sorry for the inconvenience.
