### ISSUE TITLE
GTFS import of previously exported GTFS data fails with duplicate shape data

### ISSUE THREAD

**Issue by seime** [afimb/chouette#23]
Tested with version 3.2.

Steps to reproduce:
1. Create a new data space
2. Import the attached GTFS file
3. Export data from Chouette to GTFS
4. Import the newly exported data set. Fails. See image.

<img width="874" alt="screen shot 2016-02-23 at 11 12 24" src="https://cloud.githubusercontent.com/assets/1565156/13248437/8ddf2a4c-da1e-11e5-8d35-5f9f73392bf1.png">

[akt.zip](https://github.com/afimb/chouette/files/142269/akt.zip)

**Comment by metienne** [comment]
```
 commit  b07ff56 correct GTFS shape_pt_sequence on export , close #23 issue
```
