### ISSUE TITLE
StopPointUpdater ignores certain fields

### ISSUE THREAD

**Issue by seime** [afimb/chouette#26]
When trying to store a fresh Line, the LineOptimizer will try to read all existent data from the database. In case the Line does not exist, it will create a new similar object in the cache with the objectId set. Afterwards it will copy all properties from the newValue (object created during parsing) into oldValue which is saved in the database.

However, it seems that not all values are copied: 
- forAlighting
- forBoarding

**Comment by metienne** [comment]
pull resquest merged #27
