### ISSUE TITLE
Gestion des versions

### ISSUE THREAD

**Issue by mhicauber** [afimb/chouette#5]
Bonjour,

Je travaille actuellement avec certains modules de la v3.0.0.
Cette version est-elle stable ? sinon est-il possible de mettre en place un repo de SNAPSHOT ?

En effet au fur et à mesure que j'introduis de nouveaux modules chouette dans mon application, d'autres modules ne compilent plus car le code évolue sans pour autant que la version ne bouge. Lorsque je le détecte, j'efface mon repo maven local pour forcer Maven à retélécharger les derniers jars depuis http://maven.chouette.mobi.... mais il serait plus simple d'avoir un repo de SNAPSHOTS sur ce serveur pour les développements en cours (ou bien figer une version 3.0.0 même si elle n'est pas terminée, et passer sur une 3.0.1 pour les devs en cours).

Merci d'avance de votre réponse.

Mathieu.

**Comment by metienne** [comment]
Bonjour,
la version a été stabilisée ce jour; nous allons mettre en place un repository SNAPSHOT pour les prochains développements.

Cordialement,
Michel Etienne

**Comment by mhicauber** [comment]
Très bonne nouvelle, merci de ce retour. Je laisse le ticket ouvert pour que vous puissiez y mettre les coordonnées du nouveau repo afin d'être notifié.

**Comment by mhicauber** [comment]
Bonjour,

En buildant le projet sur une nouvelle machine je constate que l'artefact http://maven.chouette.mobi/mobi/chouette/mobi.chouette.exchange.neptune/3.1.0-SNAPSHOT/ n'est plus dispo. Puis-je le trouver quelque part ?

Merci d'avance.

**Comment by metienne** [comment]
Bonjour,
les snapshots sont sur maven-snapshot.chouette.mobi
cdlt

**Comment by metienne** [comment]
Note : la version 3.1.0 sera mise en ligne demain

**Comment by mhicauber** [comment]
Merci des infos.
