### ISSUE TITLE
No more 3.4.2 release ?

### ISSUE THREAD

**Issue by mhicauber** [afimb/chouette#52]
I'm pretty sure I was using v3.4.2 in my build (pulling maven dependencies).
Now those dependencies are not found anymore in chouette maven repository ?

Thank you,

Mathieu.

**Comment by metienne** [comment]
Maybe a data lost problem; I see for it and rebuild if necessary

**Comment by mhicauber** [comment]
Edited issue, typo (talking about main maven chouette repo, tnot the snapshot one)

**Comment by metienne** [comment]
version 3.4.2-SNAPSHOT has been changed to 3.5.0-SNAPSHOT (wrong version number

**Comment by metienne** [comment]
version 3.4.2 has been republished

**Comment by mhicauber** [comment]
Thanks
